#!/bin/bash

set -e

$INPUT_ARTIFACTS_DIR/weak/qbt_fringe.wrapper_generator.release/strong/qbt_fringe.wrapper_generator.release/bin/wrapper_generator $INPUT_ARTIFACTS_DIR/weak/qbt_fringe.eclipse_gen.simple.main/strong $OUTPUT_ARTIFACTS_DIR \
    eclipse_gen.simple qbt.fringe.eclipse_gen.Simple \

